### PR TITLE
Add benchmark tests

### PR DESCRIPTION
**Pull request by kohrapha**
Add benchmarks to track package performance and compare across changes.

### CODE REVIEW

**Comment by kohrapha** [comment]
Tagging @mxiamxia for review. Not able to add you as a reviewer 🤔

**Comment by kohrapha** [comment]
Additionally, should we create a `bench.txt` file that tracks the most up-to-date benchmark that we can use to compare against for future code changes?

Then to compare, we just need to run `benchcmp` or `benchstat` to see the different in performance.

**Review by mxiamxia — APPROVED** [review]
Nice, this should also go to upstream. nice work

**Comment by kohrapha** [comment]
@mxiamxia thanks! Should this go into upstream as-is or should we add benchmarking files to track performance?

**Comment by kohrapha** [comment]
I'll merge this in for now, and if we need a benchmarking file, we can open a new CR for that in the future.

**Pull request merged**
